name: CI Pipeline

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
        with:
          ref: main
          fetch-depth: '0'

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

#      - name: Run tests
#        run: mvn -B test

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Cache SonarCloud packages
        # Caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      #Analyze project with SonarCloud
      - name: Analyze with SonarCloud
#        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=DISLINKT-ORGANIZATION_test-repo -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        run: ./mvnw -B verify sonar:sonar -Dsonar.projectKey=DISLINKT-ORGANIZATION_test-repo -Dsonar.organization=DISLINKT-ORGANIZATION -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


###################
      - name: Create a Github release
        id: release
        uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: minor
          tag_prefix: v
          release_name: "Release <RELEASE_VERSION>"









