name: CI Pipeline

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

jobs:
  ci:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
        with:
          ref: main
          fetch-depth: '0'

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          run: echo ::set-env name=JDK_11::$(echo $JAVA_HOME)

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        run: mvn -B test

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

#      - name: Specify next version
#      - name: Upload artifact
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: "main"
          git-release-bot-name: "bot-idhub"
          git-release-bot-email: "bot@idhub.io"
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip -Dmaven.deploy.skip=true"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
