name: Actions on main branch
on: 
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:    
      - 'main'

jobs:
  checks:
    name: Check PR
    runs-on: ubuntu-latest
    env:
      PR_BRANCH: ${{github.event.pull_request.head.ref}}
      DEVELOP_BRANCH: develop
    steps:
      - name: not_develop
        if: ${{ env.DEVELOP_BRANCH != env.PR_BRANCH }}
        run: exit 1
      - name: develop
        if: ${{ env.DEVELOP_BRANCH == env.PR_BRANCH }}
        run: echo "ok"


#      - name: Print github ref
#        run: echo  goalBranch - ${{github.event.pull_request.head.ref}} githubEventName - ${{ github.event_name }}
#
#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJSON(github) }}
#        run: echo ${{ env.GITHUB_CONTEXT }}
